config/routes.rb
Wahdle::Application.routes.draw do
  

  get "groups/new"

  get "groups/create"

  get "trips/new_lodgings", :controller => :trips, :action => :new_lodgings, :method => :get, :as => :new_lodgings
  get "users/new_guest", :controller => :users, :action => :new_guest, :method => :get, :as => :new_guests
  post 'trip/add_users', :controller => :trips, :action => :add_users, :as => :add_users
  post 'trip/add_lodgings', :controller => :trips, :action => :add_lodgings, :as => :add_lodgings
  post 'trip/location_search', :controller => :trips, :action => :location_search, :as => :location_search
  post 'trip/launch', :controller => :trips, :action => :launch, :as => :launch

  get "trips/show", :controller => :trips, :action => :show, :method => :get, :as => :show

  resources :users
  
  resources :lodgings
  
  root :to => "trips#new"
  
  get "sessions/new", :as => :signin
  post "sessions/create"
  delete "sessions/destroy", :as => :signout
  
  resources :trips
  resources :messages
  

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  
  has_many :joins
  has_many :users, :through => :joins
  has_many :lodgings
  
  has_many :messages
  
  
  def planner
   # User.find(self.joins.find_by_planner(true).user_id)
    Trip.includes(:users).where("joins.planner = ?", true).find(self).users.first
  end
  
  def guests
    Trip.includes(:users).where("joins.planner = ?", false).find(self).users
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  include Suitcase
    

 
  def index
    unless logged_in? 
            flash[:notice] = "Please sign in!"
            redirect_to root_url
    else
      @trips = current_user.trips.all 
    end
  end
  
  def new
    p @email=params[:email]
    p @password=params[:ref]
    
    
    if @email && @password
      user = User.find_by_email(@email)
      if user && user.authenticate(@password)
        session[:user_id] = user.id
        flash[:notice] = "Thank you for signing in!"
        redirect_to trip_url(user.trips.last.id)
       #redirect_to edit_user_url(current_user.id)
      end
    else
      @trip = Trip.new
    end
  end
  
  def show
    
    unless logged_in? 
        flash[:notice] = "Please sign in!"
        redirect_to root_url
    else      
  
    
        @trips = current_user.trips.all
    
        p "START"
        @trips.each {|i| p i.name}
        p "END"
    
        @trip = Trip.find(params[:id])
    
        @guests = @trip.users
        lodgings = @trip.lodgings
        a=[]
        lodgings.each {|i| a<<i.ean_hotel_id}
    
    
    
        @hotels = Hotel.find(:ids=>a )
        @messages = Trip.find(params[:id]).messages.all
        @message = Message.new
    
        render :layout => 'trip_layout'
    end
  end

  def create
    if @trip = Trip.create(params[:trip])
      redirect_to new_guests_path(:trip_id => @trip.id)
    else
      redirect_to new_trip_url, :notice => "You missed some things."
    end
  end
  
  def add_users
    email_list = params[:emails]
    @trip = Trip.find(params[:trip_id])
    
    email_list.each do |key, value|
      unless @user=User.find_by_email(value)
          @user= User.create(:email => value, :password => "password", :password_confirmation => "password")      
          @user.password="187100#{@user.id}"
          @user.password_confirmation="187100#{@user.id}"
          @user.save
      end
      Join.create(:user_id=>@user.id,:trip_id=>@trip.id,:planner=>false)
    end
    
    @trip.save
    redirect_to new_lodging_url(:trip_id => @trip.id)
  end
  
  def launch
    @trip = Trip.find(params[:id])
    
    unless logged_in? 
        flash[:notice] = "Please sign in!"
        redirect_to root_url
    else
        if current_user==@trip.planner
          
          @trip.guests.each do |user|
            UserMailer.welcome_email(user, @trip).deliver
          end
        else
          flash[:notice] = "User is not authorized to launch trip"
          redirect_to root_url
        end
    end
  end
  
  
  
  def location_search
    begin
      @locations = Suitcase::Hotel::Location.find(:destination_string => params[:location])
    rescue
      @locations = []
    end
    render 'autocomplete'
  end
  
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_hotel_thumbnail.html.erb
<img class="thumbnail" src=<%= object.thumbnail_url %> alt="thumb">
<span class="name"><%= object.name %></span>

app/views/trips/_message.html.erb
<tr>
	<td><%= message.user.email %></td>
	<td><%= message.text %></td>
	<td><%= time_ago_in_words(message.created_at) %> ago</td>
</tr>

app/views/trips/autocomplete.js.erb
$(document).ready(function() {
  locations = [];
  <% @locations.each do |location| %>
    locations.push("<%= location.city + ", " + location.province + ", " + location.country_code %>");
  <% end %>
  $('#hotel_location_field').autocomplete({ source: locations });
});

app/views/trips/index.html.erb
<h1>My Trips</h1>
<% @trips.each do |trip| %>
	<%= link_to trip.name, trip_url(trip) %>
<% end %>

app/views/trips/new.html.erb
<div id="quote_wrapper">
	<div id="main_quote">
		Now, group travel is easier than ever.
	</div>
	<div id="sub_quote">
		Plan an event, invite your group, pick a lodging & book!
		<a href="JavaScript:void(0);" class="button_action orange_action">Learn More</a>
	</div>	
</div>
<div id="step_wrapper">
	<div id="step_inner">
		<div id="step_header">
			<div id="steps_wrap">
				<div class="step" style="text-align:left;width:185px;">
					<div class="step_image" id="step_1_active"></div>
					<div class="clr"></div>
					Plan Event
				</div>
				<div class="step" style="text-align:center;">
					<div class="step_image" id="step_2_inactive"></div>
					Invite Guests
				</div>
				<div class="step" style="text-align:right;width:195px;">
					<div class="step_image" id="step_3_inactive"></div>
					<div class="clr"></div>
					Lodging Selection
				</div>
				<div class="clr"></div>
			</div>
		</div>
		<div id="step_main">
			<div id="step_box">
				<div id="loops_wrap">
					<div class="loop" style="float:left;"></div>
					<div class="loop" style="float:right;"></div>
					<div class="clr"></div>
				</div>
				<%= form_for @trip do |form| %>
				<div id="step_box_content">
						<div class="input_names">
							<div class="name"><%= form.label :name, "Name:" %></div>
							<div class="name"><%= form.label :destination, "Where:" %></div>
							<div class="name">When:</div>
						</div>
						<div class="input_boxes">
							<%= form.text_field :name, :placeholder => "ie. Ben's Ski Trip" %>
							<%= form.text_field(:destination, :placeholder => "ie. Colorado", :id => "hotel_location_field") %>
						</div>	
						<div class="clr"></div>
						<div id="datepicker_wrap">
							<div id="trip_starts_on_picker"></div>
							<div id="trip_ends_on_picker"></div>
							<%= form.hidden_field :starts_on %>
							<%= form.hidden_field :ends_on %>
							<div class="clr"></div>
						</div>								
						<div class="clr"></div>
					</div>
					<div id="step_box_footer" style="padding:10px 160px 0;">
						Let's do this...
						<%= form.submit "Invite Guests", :class => "button_action blue_action", :style => "float:right" %> 
					</div>
				<% end %>	
			</div>
		</div>
	</div>
</div>

app/views/trips/show.html.erb
<!--START SHOW TRIP HTML****************************************************-->
<div id="trip_header">
	<div id="trip_header_inner">
		<div id="trip_name">
			Trip: <%= @trip.name %>  	
			<span id='launch'>
			<%= form_tag launch_path(:id => params[:id]) do %>
			<%= submit_tag "Launch Trip", :class => "button_action blue_action", :style => "float:right" %>
			<% 	end %>
			</span>
			
			<% if flash[:warning] or flash[:notice] %>
				<div id="trip_notice"> <%= notice %></div>
			<% end %>
		</div>

	</div>
</div>
<div id="trip_details_wrapper">
	<div id="trip_details_inner">
		<div class="trip_column" id="left_column">
	 		<div class="trip_select_container">
				<%= form_tag(show_url, :method=>'get', :multipart => false) do %>
				 <%= select_tag("id", options_from_collection_for_select(@trips, "id", "name", @trip.id),{ :onchange => "this.form.submit();"}) %>
				 <%= link_to "New", root_path %>
				<% end %>
			
				
			</div>
			
			<div class="content_box">
				<div class="content_header">
					Trip Info
				</div>
				<div class="content">
					<div class="content_row">
					
						<span class="title">Name:</span><%= "#{@trip.name}"  %>
					</div>
					<div class="content_row">
						<span class="title">City:</span><%= @trip.destination %>
					</div>
					<div class="content_row">
						<span class="title">Starts:</span><%= @trip.starts_on %>
					</div>
					<div class="content_row">
						<span class="title">Ends:</span><%= @trip.ends_on %>
					</div>
				</div>
			</div>
			<div class="content_box">
				<div class="content_header">
					Guest List
				</div>
				<div class="content">
					<% @guests.each do |guest| %>
						<div class="content_row">
							<%= guest.email %>
						</div>
					<% end %>
				</div>
			</div>
		</div>
		<div class="trip_column" id="middle_column">
			<div id="message_wrapper">
				<div id="message_header">
					<%= form_for @message, :url => messages_url(:id => @trip.id) do |form| %>
					<%= form.text_field :text, :placeholder => "Post a message" %>
					<%= form.submit "Post", :class => "blue_action button_action" %>
					<% end %>
				</div>
				<div id="message_content">
					<% @messages.each do |message|%>
					<div class="comment_box">
						<span class="name"><%= message.user.email %> says: </span><%= message.text %>
						<span class="time"><%= time_ago_in_words(message.created_at) %> ago</span>
					</div>
					<% end %>
				</div>
			</div>
		</div>
		<div class="trip_column" id="right_column">
			<div class="content_box">
				<div class="content_header">
					Lodging List
				</div>
				<ul class="content">
					<% @hotels.each do |h|%>
						<li>
							<%= 	render(	:partial => "/trips/hotel_thumbnail", 
											:locals => { :object => h})%>
						</li>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="clr"></div>
	</div>		
</div>
	





	
	