config/routes.rb
Wahdle::Application.routes.draw do
  

  get "groups/new"

  get "groups/create"

  get "trips/new_lodgings", :controller => :trips, :action => :new_lodgings, :method => :get, :as => :new_lodgings
  get "users/new_guest", :controller => :users, :action => :new_guest, :method => :get, :as => :new_guests
  post 'trip/add_users', :controller => :trips, :action => :add_users, :as => :add_users
  post 'trip/add_lodgings', :controller => :trips, :action => :add_lodgings, :as => :add_lodgings
  post 'trip/location_search', :controller => :trips, :action => :location_search, :as => :location_search
  post 'trip/launch', :controller => :trips, :action => :launch, :as => :launch

  get "trips/show", :controller => :trips, :action => :show, :method => :get, :as => :show

  resources :users
  
  resources :lodgings
  
  root :to => "trips#new"
  
  get "sessions/new", :as => :signin
  post "sessions/create"
  delete "sessions/destroy", :as => :signout
  
  resources :trips
  resources :messages
  

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
  belongs_to :group
  
  default_scope :order => "created_at DESC"
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :trip
  before_filter :new_message, only: [:new, :index]
  before_filter :trip_messages, only: [:index]
    
  def create
    @message = current_user.messages.build(params[:message].merge(trip_id: @trip.id))
    message = (@message.save ? "Posted!" : "Try again!")
    redirect_to @trip, notice: message
  end
  
  private
  def new_message
    @message ||= Message.new
  end
  
  def trip_messages
    @messages ||= trip.messages
  end
  
  def trip
    @trip ||= Trip.find(params[:id])
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<h1>Wahdle Wall</h1>

<table><%= render @messages %></table>

<h1>Write a message</h1>
<%= form_for @message, :url => trip_messages_url(params[:trip_id]), :method => :post do |form| %>
	<div class="field">
		<%= form.label :text %> <br />
		<%= form.text_area :text, :rows => 3 %>
	</div>
	<div class="action">
		<%= form.submit "Post" %>
	</div>
<% end %>

app/views/messages/new.html.erb
<h1>Write a message</h1>
<%= form_for @message do |form| %>
	<div class="field">
		<%= form.label :text %> <br />
		<%= form.text_area :text, :rows => 3 %>
	</div>
	<div class="action">
		<%= form.submit "Post" %>
	</div>
<% end %>