config/routes.rb
Wahdle::Application.routes.draw do
  

  get "groups/new"

  get "groups/create"

  get "trips/new_lodgings", :controller => :trips, :action => :new_lodgings, :method => :get, :as => :new_lodgings
  get "users/new_guest", :controller => :users, :action => :new_guest, :method => :get, :as => :new_guests
  post 'trip/add_users', :controller => :trips, :action => :add_users, :as => :add_users
  post 'trip/add_lodgings', :controller => :trips, :action => :add_lodgings, :as => :add_lodgings
  post 'trip/location_search', :controller => :trips, :action => :location_search, :as => :location_search
  post 'trip/launch', :controller => :trips, :action => :launch, :as => :launch

  get "trips/show", :controller => :trips, :action => :show, :method => :get, :as => :show

  resources :users
  
  resources :lodgings
  
  root :to => "trips#new"
  
  get "sessions/new", :as => :signin
  post "sessions/create"
  delete "sessions/destroy", :as => :signout
  
  resources :trips
  resources :messages
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :joins  
  has_many :trips, :through => :joins
  has_many :messages
  belongs_to :group
  
  validates_presence_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
 
  def new
    @user = User.new
  end
  
  def create
    
    
 
    @trip = Trip.find(params[:trip_id])
    
    
    # Look for existing user my email... if not found create new user
    @user= current_user || User.find_by_email(params[:user][:email])|| User.new(params[:user])
    
    if @user.save
      session[:user_id] = @user.id
      Join.create(:user_id=>@user.id,:trip_id=>@trip.id,:planner=>TRUE)
      p "SAVED JOIN #{@user.id}, #{@trip.id}"  
      flash[:notice] = "Thanks for signing up!"
      redirect_to trip_url(params[:trip_id])
    else
      flash[:notice] = "Please try to sign up again."
      render :new
    end
  end
  
  def new_guest
  end
  
   # GET /users/1/edit
  def edit
    @user = User.find(params[:id])

    unless logged_in? && current_user==@user
            redirect_to root_url
            flash[:notice] = "Please sign in!"
    end
    
  end
  
  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to trip_url(@user.trips.last.id), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def show
    
    @trips = Array.new
    Join.find_all_by_user_id(current_user.id).each do |join|
    @trips << join.trip
    end
    render :layout => 'trip_layout'
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div id="quote_wrapper">
	<div id="main_quote">
		Now, group travel is easier than ever.
	</div>
	<div id="sub_quote">
		Plan an event, invite your group, pick a lodging & book!
		<a href="JavaScript:void(0);" class="button_action orange_action">Learn More</a>
	</div>	
</div>
<div id="step_wrapper">
	<div id="step_inner">
		<div id="step_header">
			<div id="steps_quote">
				Please Create/Edit your account!
			</div>
		</div>
		<div id="step_main">
			<div id="step_box">
				<div id="loops_wrap">
					<div class="loop" style="float:left;"></div>
					<div class="loop" style="float:right;"></div>
					<div class="clr"></div>
				</div>
				<div id="step_box_content">
					<%= form_for @user do |form| %>
						<div class="input_names">
							<div class="name"><%= form.label :name%>:</div>
							<div class="name"><%= form.label :email%>:</div>
							<div class="name"><%= form.label :password %>:</div>
							<div class="name"><%= form.label :password_confirmation, "Again" %>:</div>
						</div>
						<div class="input_boxes">
							<%= form.text_field :name, :placeholder => "John Doe" %>
							<%= form.text_field :email, :placeholder => "johndoe@example.com" %>
							<%= form.password_field :password, :placeholder => "" %>
							<%= form.password_field :password_confirmation, :placeholder => ""%>
						</div>									
						<div class="clr"></div>
					</div>
					<div id="step_box_footer" style="padding:10px 160px 0;">
						Let's do this...
						<%= form.submit "Create Account", :class => "button_action blue_action", :style => "float:right" %>
					</div>
				<% end %>	
			</div>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div id="quote_wrapper">
	<div id="main_quote">
		Now, group travel is easier than ever.
	</div>
	<div id="sub_quote">
		Plan an event, invite your group, pick a lodging & book!
		<a href="JavaScript:void(0);" class="button_action orange_action">Learn More</a>
	</div>	
</div>
<div id="step_wrapper">
	<div id="step_inner">
		<div id="step_header">
			<div id="steps_quote">
				Please Create an account First!
			</div>
		</div>
		<div id="step_main">
			<div id="step_box">
				<div id="loops_wrap">
					<div class="loop" style="float:left;"></div>
					<div class="loop" style="float:right;"></div>
					<div class="clr"></div>
				</div>
				<div id="step_box_content">
					<%= form_for @user, :url => users_url(:trip_id => params[:trip_id]) do |form| %>
						<div class="input_names">
							<div class="name"><%= form.label :name%>:</div>
							<div class="name"><%= form.label :email%>:</div>
							<div class="name"><%= form.label :password %>:</div>
							<div class="name"><%= form.label :password_confirmation, "Again" %>:</div>
						</div>
						<div class="input_boxes">
							<%= form.text_field :name, :placeholder => "John Doe" %>
							<%= form.text_field :email, :placeholder => "johndoe@example.com" %>
							<%= form.password_field :password, :placeholder => "" %>
							<%= form.password_field :password_confirmation, :placeholder => ""%>
						</div>									
						<div class="clr"></div>
					</div>
					<div id="step_box_footer" style="padding:10px 160px 0;">
						Let's do this...
						<%= form.submit "Create Account", :class => "button_action blue_action", :style => "float:right" %>
					</div>
				<% end %>	
			</div>
		</div>
	</div>
</div>

app/views/users/new_guest.html.erb
<div id="quote_wrapper">
	<div id="main_quote">
		Now, group travel is easier than ever.
	</div>
	<div id="sub_quote">
		Plan an event, invite your group, pick a lodging & book!
		<a href="JavaScript:void(0);" class="button_action orange_action">Learn More</a>
	</div>	
</div>
<div id="step_wrapper">
	<div id="step_inner">
		<div id="step_header">
			<div id="steps_wrap">
				<div class="step" style="text-align:left;width:185px;">
					<div class="step_image" id="step_1_active"></div>
					<div class="clr"></div>
					Plan Event
				</div>
				<div class="step" style="text-align:center;">
					<div class="step_image" id="step_2_active"></div>
					Invite Guests
				</div>
				<div class="step" style="text-align:right;width:195px;">
					<div class="step_image" id="step_3_inactive"></div>
					<div class="clr"></div>
					Lodging Search
				</div>
				<div class="clr"></div>
			</div>
		</div>
		<div id="step_main">
			<div id="step_box">
				<div id="loops_wrap">
					<div class="loop" style="float:left;"></div>
					<div class="loop" style="float:right;"></div>
					<div class="clr"></div>
				</div>
				<div id="step_box_content">
					<%= form_tag add_users_path(:trip_id => params[:trip_id]) do %>
						<div class="input_names" id="guest_labels">
							<div class="name"><label>Guest 1</label></div>
							<div class="name"><label>Guest 2</label></div>
							<div class="name"><label>Guest 3</label></div>
							<div class="name"><label>Guest 4</label></div>
						</div>
						<div class="input_boxes" id="guest_inputs">
							<%= text_field :emails, :"0", :placeholder => "guest1@example.com" %>
							<%= text_field :emails, :"1", :placeholder => "guest2@example.com" %>
							<%= text_field :emails, :"2", :placeholder => "guest3@example.com" %>
							<%= text_field :emails, :"3", :placeholder => "guest4@example.com" %>
						</div>									
						<a href="JavaScript:void(0);" id="add_guest" class="button_action orange_action" style="float:left;margin-left:10px;">Add more</a>
						<div class="clr"></div>
					</div>
					<div id="step_box_footer" style="padding:10px 110px 0;">
						Send out some invites...
						<%= submit_tag "Invite Guests", :class => "button_action blue_action", :style => "float:right" %>
					</div>
				<% end %>	
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
	  <% @trips.each do |t| %>
      <li><%= link_to t.name, trip_url(t) %></li>
    <% end %>
	