config/routes.rb
Wahdle::Application.routes.draw do
  

  get "groups/new"

  get "groups/create"

  get "trips/new_lodgings", :controller => :trips, :action => :new_lodgings, :method => :get, :as => :new_lodgings
  get "users/new_guest", :controller => :users, :action => :new_guest, :method => :get, :as => :new_guests
  post 'trip/add_users', :controller => :trips, :action => :add_users, :as => :add_users
  post 'trip/add_lodgings', :controller => :trips, :action => :add_lodgings, :as => :add_lodgings
  post 'trip/location_search', :controller => :trips, :action => :location_search, :as => :location_search
  post 'trip/launch', :controller => :trips, :action => :launch, :as => :launch

  get "trips/show", :controller => :trips, :action => :show, :method => :get, :as => :show

  resources :users
  
  resources :lodgings
  
  root :to => "trips#new"
  
  get "sessions/new", :as => :signin
  post "sessions/create"
  delete "sessions/destroy", :as => :signout
  
  resources :trips
  resources :messages
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wahdle</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header_wrapper">
		<div id="header_inner">
			<div id="main_logo"></div>
			
			<div id="session_box">
				
				<% if logged_in? %>
					<div class="session_label">Hello, <%= current_user.email %>! | <%= link_to "My Trips", current_user_trips_url%> </div>
					<%= link_to "Sign Out", signout_url, :method => :delete, :class => "button_action orange_action", :style => "height:23px; line-height:23px; font-size:14px; float:right; margin-left:10px;"  %>
				<% else  %>				

					<%= form_tag sessions_create_url do %>
							<div class="session_label">Email:</div>
							<%= text_field_tag(:email,@email) %>
							<div class="session_label">Password:</div>			
							<%= password_field_tag(:password, @password)%>
							<%= submit_tag "Sign in!", :class => "button_action blue_action", :style => "height:23px; line-height:23px; font-size:14px; float:right; margin-left:10px;" %>
					<% end %>
				<% end  %>
				
			</div>
		</div>
	</div>
		<div id="main_banner">
			<div id="city_scape">
				
				<% if flash[:warning] or flash[:notice] %>
					<div id="app_notice"> <%= notice %></div>
				<% end %>
				
				<%= yield %>
			</div>		
		</div>
	</div>
	<div id="navigation">
		<div id="navigation_inner">
			<div id="navigation_links">
				<span>Wahdle 2011</span> |
				<a href="JavaScript:void(0);">About Us</a> |
				<a href="JavaScript:void(0);">Customer Support</a> |
				<a href="JavaScript:void(0);">Contact</a> |
				<a href="JavaScript:void(0);">Jobs</a>
			</div>
		</div>
	</div>	
	<div id="main_description">
		<div id="description_tagline">
			How does Wahdle work?
			<div id="minor_tag">Well, it's super easy. We'll explain it in three basic steps:</div>
		</div>
		<div id="description_columns">
			<div class="column">
				<div class="column_image" id="description_1"></div>
				<div class="column_header">
					This is you.
				</div>
				<div class="column_text">
					You want to plan a party, a get-together, a baby shower, a bachelor bash, a small pool party, game night, a flash mob....you get the idea. You want to invite as many or as few as you want. You want to hold the cards and keep it organized.
				</div>
			</div>
			<div class="column">
				<div class="column_image" id="description_2"></div>
				<div class="column_header">
					This is Wahdle.
				</div>
				<div class="column_text">
					Wahdle is the go-between, the meeting place, the ultimate mediator. Wahdle is a sophisticated organizing machine sent
from the future to make sure your event is awesome and your guests are happy. 
Everyone has a say, but you have the 
administrative power.
				</div>
			</div>
			<div class="column">
				<div class="column_image" id="description_3"></div>
				<div class="column_header">
					These are your guests.
				</div>
				<div class="column_text">
					Your guests are separated into two groups: those who want to bombard you with their ideas and those who are glad you’re taking the reins. Wahdle helps synthesize feedback by removing hundreds of CC emails from friends and letting the quiet folks sit back and watch the event planning go down from afar.
				</div>
			</div>
			<div class="clr"></div>
		</div>
</body>
</html>

app/views/layouts/trip_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wahdle</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header_wrapper">
		<div id="header_inner">
			<div id="main_logo"></div>
			
			<div id="session_box">
				<% if logged_in? %>
					<div class="session_label">Hello, <%= current_user.email %>! | <%= link_to "My Profile", edit_user_url(current_user.id)%></div>
					<%= link_to "Sign Out", signout_url, :method => :delete, :class => "button_action orange_action", :style => "height:23px; line-height:23px; font-size:14px; float:right; margin-left:10px;"  %>
				<% else  %>				
					<%= form_tag sessions_create_url do %>
							<div class="session_label">Email:</div>
							<%= text_field_tag('email',@email) %>
							<div class="session_label">Password:</div>			
							<%= password_field_tag(:password, @password)%>
							<%= submit_tag "Sign in!", :class => "button_action blue_action", :style => "height:23px; line-height:23px; font-size:14px; float:right; margin-left:10px;" %>
					<% end %>
				<% end  %>
			</div>
		</div>
	</div>
	<%= yield %>
	<div id="navigation">
		<div id="navigation_inner">
			<div id="navigation_links">
				<span>Wahdle 2011</span> |
				<a href="JavaScript:void(0);">About Us</a> |
				<a href="JavaScript:void(0);">Customer Support</a> |
				<a href="JavaScript:void(0);">Contact</a> |
				<a href="JavaScript:void(0);">Jobs</a>
			</div>
		</div>
	</div>
</body>
</html>